DoAn2/Controllers/AdminDatHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn2.Models;

namespace WebBanSach.Controllers
{
   
    public class AdminDatHangController : Controller
    {
        private NhaSachDbContext db = new NhaSachDbContext();

        // GET: AdminDatHang
        public ActionResult Index()
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                return View(db.DatHangs.ToList());
            }
            else
                return RedirectToAction("Login", "AdminUser");            
        }

        #region Chi tiết
        // GET: AdminDatHang/Details/5
        public ActionResult Details(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DatHang datHang = db.DatHangs.Find(id);
                if (datHang == null)
                {
                    return HttpNotFound();
                }
                return View(datHang);
            }
            else
                return RedirectToAction("Login", "AdminUser");           
        }
        #endregion

        #region Sửa
        // GET: AdminDatHang/Edit/5
        public ActionResult Edit(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DatHang datHang = db.DatHangs.Find(id);
                if (datHang == null)
                {
                    return HttpNotFound();
                }
                return View(datHang);
            }
            else
                return RedirectToAction("Login", "AdminUser");           
        }

        // POST: AdminDatHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DatHangID,KhachHangID,NgayDatHang,TriGia,DaGiao,NgayGiao,HoTen,DiaChi,DienThoai,Email")] DatHang datHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(datHang);
        }
        #endregion

        #region Giải phóng biến
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

DoAn2/Views/AdminDatHang/Details.cshtml
@model DoAn2.Models.DatHang

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Đơn hàng</h4>
    <hr />
    <dl class="dl-horizontal">
       

      

        <dt>
            @Html.DisplayNameFor(model => model.NgayDatHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDatHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TriGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TriGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.DatHangID }) |
    @Html.ActionLink("Quay về", "Index") |
    @Html.ActionLink("Xuất Hóa Đơn", "XuatExcel", "AdminDatHang")
    
</p>

DoAn2/Views/AdminDatHang/Edit.cshtml
@model DoAn2.Models.DatHang

@{
    ViewBag.Title = "Sửa";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Đơn hàng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DatHangID)


        <div class="form-group">
            @Html.LabelFor(model => model.NgayDatHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDatHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDatHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TriGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TriGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TriGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DaGiao)
                    @Html.ValidationMessageFor(model => model.DaGiao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ghi" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAn2/Views/AdminDatHang/Index.cshtml
@model IEnumerable<DoAn2.Models.DatHang>

@{
    ViewBag.Title = "Danh sách đơn hàng";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Danh sách đơn hàng</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="display" style="width:100%">
                    <thead>
                        <tr>
                            
                            <th>
                                @Html.DisplayNameFor(model => model.NgayDatHang)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TriGia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DaGiao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NgayGiao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.HoTen)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DiaChi)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DienThoai)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                           
                            <th>
                                @Html.DisplayNameFor(model => model.NgayDatHang)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TriGia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DaGiao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NgayGiao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.HoTen)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DiaChi)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DienThoai)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                               
                                <td>
                                    @Html.DisplayFor(modelItem => item.NgayDatHang)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TriGia)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DaGiao)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NgayGiao)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.HoTen)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DiaChi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DienThoai)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.DatHangID }) |
                                    @Html.ActionLink("Xem", "Details", new { id = item.DatHangID }) |
                                    @Html.ActionLink("Xuất Hóa Đơn", "ExportToExcel" , "AdminDatHangCT" , new { id = item.DatHangID },null)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

                    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
                    <script>
                        $(document).ready(function () {
                            $('#dataTable').DataTable();
                        });
                    </script>
                }