DoAn2/Controllers/AdminSachController.cs
using DoAn2.Models;
using DoAn2.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DoAn2.Controllers
{
    public class AdminSachController : Controller
    {
        private NhaSachDbContext db = new NhaSachDbContext();
        // GET: AdminSach
        public ActionResult Index()
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                var saches = db.Saches.Where(x => x.HetHang == false);
                return View(saches.ToList());
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }

        #region Chi tiết
        // GET: AdminSach/Details/5
        public ActionResult Details(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sach sach = db.Saches.Find(id);
                if (sach == null)
                {
                    return HttpNotFound();
                }
                return View(sach);
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }
        #endregion

        #region Thêm
        // GET: AdminSach/Create
        public ActionResult Create()
        {
            //var item = db.Saches.ToList().Count();
            //Console.log(typeof item);
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe");
                ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans, "NhaXuatBanID", "TenNhaXuatBan");
                return View();
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }

        // POST: AdminSach/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TenSach,GiaBan,MaChuDe,NhaXuatBanID,MoTa,HinhBia,SoTrang,TrongLuong,NgayCapNhat,SoLanXem,SoLuongBan,HetHang")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                //var str = db.Saches.ToList().Count() + 1;
                //sach.SachID = str;
                sach.NgayCapNhat = DateTime.Now;
                db.Saches.Add(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans, "NhaXuatBanID", "TenNhaXuatBan", sach.NhaXuatBanID);
            return View(sach);
        }
        #endregion

        #region Sửa
        // GET: AdminSach/Edit/5
        public ActionResult Edit(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sach sach = db.Saches.Find(id);
                if (sach == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", sach.MaChuDe);
                ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans, "NhaXuatBanID", "TenNhaXuatBan", sach.NhaXuatBanID);
                return View(sach);
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }

        // POST: AdminSach/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SachID,TenSach,GiaBan,MaChuDe,NhaXuatBanID,MoTa,HinhBia,SoTrang,TrongLuong,NgayCapNhat,SoLanXem,SoLuongBan,HetHang")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans, "NhaXuatBanID", "TenNhaXuatBan", sach.NhaXuatBanID);
            return View(sach);
        }
        #endregion

        #region Xóa

        // GET: AdminSach/Delete/5
        public ActionResult Delete(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                if (nguoiDung.UserRole.RoleID == 1 || nguoiDung.UserRole.RoleID == 2)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Sach sach = db.Saches.Find(id);
                    if (sach == null)
                    {
                        return HttpNotFound();
                    }
                    return View(sach);
                }
                else
                    return RedirectToAction("Login", "AdminUser");
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }

        // POST: AdminSach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sach sach = db.Saches.Find(id);
            sach.HetHang = true;
            db.Entry(sach).State = EntityState.Modified;
            db.SaveChanges();


            var nguoiDung = Session["NguoiDung"] as User;
            var listLog = Session["Log"] as LogModel;
            if (listLog == null)
            {
                listLog = new LogModel();
                Session["Log"] = listLog;
            }
            LogItem logItem = new LogItem();
            logItem.ThongBao = $"Người dùng {nguoiDung.TaiKhoan} đã xóa sản phẩm có ID= {id}";
            logItem.ThoiGian = DateTime.Now;
            listLog.Add(logItem);


            return RedirectToAction("Index");
        }
        #endregion

        #region Giải phóng biến
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion


        #region Xử lý Upload hình
        // GET: AdminSanPham/Upload/5
        public ActionResult Upload(int? id)
        {
            User nguoiDung = Session["NguoiDung"] as User;
            if (nguoiDung != null)
            {
                try
                {
                    Sach sach = db.Saches.Find(id);
                    if (sach == null) throw new Exception($"Sản phẩm ID = " + id + " không tồn tại!!!");
                    return View(sach);
                }
                catch (Exception ex)
                {
                    object cauThongBao = $"Lỗi truy cập dữ liệu.<br/>Lý do: {ex.Message}";
                    return View("Error2", cauThongBao);
                }
            }
            else
                return RedirectToAction("Login", "AdminUser");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(int? id, HttpPostedFileBase tapTin)
        {
            try
            {
                Sach sach = db.Saches.Find(id);
                if (tapTin != null && tapTin.ContentLength > 0)
                {
                    string duongDan = Server.MapPath("~/Images/");
                    string tenHinh = string.Format("{0}{1}", sach.SachID, Path.GetExtension(tapTin.FileName));
                    tapTin.SaveAs(duongDan + tenHinh);
                    if (sach.HinhBia != null && sach.HinhBia != tenHinh)
                    {
                        System.IO.File.Delete(duongDan + sach.HinhBia);
                    }
                    sach.HinhBia = tenHinh;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ThongBao = "Bạn chưa chọn file hoặc file bạn chọn không có nội dung";
                return View(sach);
            }
            catch (Exception ex)
            {
                object cauThongBao = $"Lỗi truy cập dữ liệu.<br/>Lý do: {ex.Message}";
                return View("Error2", cauThongBao);
            }
        }
        #endregion
    }
}

DoAn2/Views/AdminSach/Create.cshtml
@model DoAn2.Models.Sach

@{
    ViewBag.Title = "Thêm sách mới";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Tạo mới</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sách</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, "MaChuDe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhaXuatBanID, "NhaXuatBanID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NhaXuatBanID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NhaXuatBanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.HinhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhBia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhBia, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.SoTrang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrongLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrongLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.SoLanXem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLanXem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLanXem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HetHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HetHang)
                    @Html.ValidationMessageFor(model => model.HetHang, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAn2/Views/AdminSach/Delete.cshtml
@model DoAn2.Models.Sach

@{
    ViewBag.Title = "Xác nhận xóa";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3>Bạn có muốn xóa @Model.TenSach ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNhaXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNhaXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrongLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrongLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLanXem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLanXem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HetHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HetHang)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay về", "Index")
        </div>
    }
</div>

DoAn2/Views/AdminSach/Details.cshtml
@model DoAn2.Models.Sach

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Sách</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNhaXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNhaXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrongLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrongLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLanXem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLanXem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HetHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HetHang)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.SachID }) |
    @Html.ActionLink("Quay về", "Index")
</p>

DoAn2/Views/AdminSach/Edit.cshtml
@model DoAn2.Models.Sach

@{
    ViewBag.Title = "Sửa";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sách</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SachID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, "MaChuDe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhaXuatBanID, "NhaXuatBanID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NhaXuatBanID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NhaXuatBanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhBia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhBia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTrang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrongLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrongLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLanXem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLanXem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLanXem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HetHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HetHang)
                    @Html.ValidationMessageFor(model => model.HetHang, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ghi" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAn2/Views/AdminSach/Upload.cshtml
@model DoAn2.Models.Sach 
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Upload hình cho sản phẩm </h2>
<div class="text-danger"> @ViewBag.ThongBao</div>

@using (Html.BeginForm("Upload", "AdminSach", FormMethod.Post,htmlAttributes: new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="file" name="taptin" id="HinhBia" />
    <input type="submit" value="Upload hình" />
}