DoAn2/Controllers/KhachHangUserController.cs
using DoAn2.Models;
using DoAn2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace DoAn2.Controllers
{
    public class KhachHangUserController : Controller
    {
        NhaSachDbContext db = new NhaSachDbContext();

        // GET: KhachHangUser

        #region Đăng ký
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult DangKy(UserKH model)
        {
            if (ModelState.IsValid)
            {
                
                var xuly = new XuLyUser();
                if (xuly.CheckTaiKhoan(model.TaiKhoan))
                { ModelState.AddModelError("", "Tên đăng nhập đã tồn tại"); }
                else if (xuly.CheckEmail(model.Email))
                { ModelState.AddModelError("", "Email đã tồn tại"); }
                else
                {
                    var user = new UserKH();
                    user.TaiKhoan = model.TaiKhoan;
                    user.ConfirmPassword = model.ConfirmPassword;
                    user.Ten = model.Ten;
                    user.PassWord = model.PassWord;
                    user.DienThoai = model.DienThoai;
                    user.Email = model.Email;
                    user.DiaChi = model.DiaChi;
                    user.NgayTao = DateTime.Now;
                    user.TrangThai = true;
                    if (!string.IsNullOrEmpty(model.TinhThanh))
                    {
                        user.TinhThanh = model.TinhThanh;
                    }
                    if (!string.IsNullOrEmpty(model.QuanHuyen))
                    {
                        user.QuanHuyen = model.QuanHuyen;
                    }
                    var result = Insert(user);
                    if (result != null)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new UserKH();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View("DangNhap", model);
        }
        #endregion

        #region đăng nhập/xuất
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }


        [HttpPost]
        public ActionResult DangNhap(UserKH user)
        {
            var item = db.UserKHs.SingleOrDefault(x => x.TaiKhoan == user.TaiKhoan );
            if(item==null)
            {
                ModelState.AddModelError("", "Tài khoản không tồn tại.");
                
            }
            else
            {
                if(item.TrangThai==false)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else
                {
                    if(item.PassWord==user.PassWord)
                    {
                        
                        Session["NguoiDung"] = item;
                        
                        return RedirectToAction("Index","Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Mật khẩu không đúng.");
                    }
                }
            }
           
            return View();
        }

        public ActionResult DangXuat()
        {
            //var nguoiDung = Session["NguoiDung"] as UserKH;
            
            Session["NguoiDung"] = null;
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region Load tỉnh thành quận huyện
        public JsonResult LoadProvince()
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/Data/Provinces_Data.xml"));

            var xElements = xmlDoc.Element("Root").Elements("Item").Where(x => x.Attribute("type").Value == "province");
            var list = new List<ProvinceModel>();
            ProvinceModel province = null;
            foreach (var item in xElements)
            {
                province = new ProvinceModel();
                province.ID = int.Parse(item.Attribute("id").Value);
                province.Name = item.Attribute("value").Value;
                list.Add(province);

            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public JsonResult LoadDistrict(int provinceID)
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/Data/Provinces_Data.xml"));

            var xElement = xmlDoc.Element("Root").Elements("Item")
                .Single(x => x.Attribute("type").Value == "province" && int.Parse(x.Attribute("id").Value) == provinceID);

            var list = new List<DistrictModel>();
            DistrictModel district = null;
            foreach (var item in xElement.Elements("Item").Where(x => x.Attribute("type").Value == "district"))
            {
                district = new DistrictModel();
                district.ID = int.Parse(item.Attribute("id").Value);
                district.Name = item.Attribute("value").Value;
                district.ProvinceID = int.Parse(xElement.Attribute("id").Value);
                list.Add(district);

            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public async Task<long> Insert(UserKH entity)
        {
            db.UserKHs.Add(entity);
            await db.SaveChangesAsync();
            return entity.ID;
        }
        #endregion
    }
}

DoAn2/Views/KhachHangUser/DangKy.cshtml
@model DoAn2.Models.UserKH
@*@using BotDetect.Web.UI.Mvc;
    <link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl"
          rel="stylesheet" type="text/css" />
    @{ MvcCaptcha registerCapcha = new MvcCaptcha("registerCapcha"); }*@

@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Data/userKhController.js"></script>
@*@section jsFooter{
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Data/userKhController.js"></script>

}*@
<div class="content">
    @using (Html.BeginForm("DangKy", "KhachHangUser", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Đăng ký thành viên</h4>
            <hr />
            <div class="form-group">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success">@ViewBag.Success</div>
                }
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TaiKhoan, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.TaiKhoan, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PassWord, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.PassWord, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Ten, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.DiaChi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.DienThoai, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TinhThanh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TinhThanh", new SelectList(new string[] { }), new { @class = "form-control", @id = "ddlProvince", @onClick = "loadDistrict(value)" })
                    @Html.ValidationMessageFor(model => model.TinhThanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuanHuyen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("QuanHuyen", new SelectList(new string[] { }), new { @class = "form-control", @id = "ddlDistrict" })
                    @Html.ValidationMessageFor(model => model.QuanHuyen, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.Captcha(registerCapcha)
                        @Html.TextBox("CaptchaCode")
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Đăng ký" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        loadProvince()
    });
</script>

DoAn2/Views/KhachHangUser/DangNhap.cshtml
@model DoAn2.Models.UserKH

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Data/userKhController.js"></script>


<!-- Content
        ============================================= -->
<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="tabs divcenter nobottommargin clearfix" id="tab-login-register" style="max-width: 500px;">

                <ul class="tab-nav tab-nav2 center clearfix">
                    <li class="inline-block"><a href="#tab-login">Đăng Nhập</a></li>
                    <li class="inline-block"><a href="#tab-register">Đăng Ký</a></li>
                </ul>

                <div class="tab-container">

                    <div class="tab-content clearfix" id="tab-login">
                        <div class="panel panel-default nobottommargin">
                            <div class="panel-body" style="padding: 40px;">
                                @using (Html.BeginForm("DangNhap", "KhachHangUser", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <form id="login-form" name="login-form" class="nobottommargin" action="#" method="post">

                                        <h3>Đăng Nhập Tài Khoản</h3>

                                        <div class="col_full">
                                            <label for="login-form-username">Tài Khoản:</label>
                                            @Html.TextBoxFor(model => model.TaiKhoan, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col_full">
                                            <label for="login-form-password">Mật Khẩu:</label>
                                            @Html.PasswordFor(model => model.PassWord, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                                        </div>
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="col_full nobottommargin">
                                            <button class="button button-3d button-black nomargin" id="login-form-submit" name="login-form-submit" value="login">Đăng Nhập</button>
                                            <a href="#" class="fright">Quên Mật Khẩu</a>
                                        </div>

                                        <div class="line line-sm"></div>

                                        <div class="center">
                                            <h4 style="margin-bottom: 15px;">Đăng Nhập Bằng:</h4>
                                            <a href="#" class="button button-rounded si-facebook si-colored">Facebook</a>
                                            <span class="hidden-xs">hoặc</span>
                                            <a href="#" class="button button-rounded si-twitter si-colored">Twitter</a>
                                        </div>
                                    </form>
                                }
                            </div>
                        </div>
                    </div>

                    <div class="tab-content clearfix" id="tab-register">
                        <div class="panel panel-default nobottommargin">
                            <div class="panel-body" style="padding: 40px;">
                                <h3>Tạo Tài Khoản</h3>
                                @using (Html.BeginForm("DangKy", "KhachHangUser", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()

                                <form id="register-form" name="register-form" class="nobottommargin" action="#" method="post">

                                    <div class="col_full">
                                        <label for="register-form-name">Tài Khoản:</label>
                                        @Html.TextBoxFor(model => model.TaiKhoan, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-email">Mật Khẩu:</label>
                                        @Html.PasswordFor(model => model.PassWord, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-username">Xác Nhận Mật Khẩu:</label>
                                        @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-phone">Tên:</label>
                                        @Html.TextBoxFor(model => model.Ten, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-password">Địa Chỉ:</label>
                                        @Html.TextAreaFor(model => model.DiaChi, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-repassword">Email:</label>
                                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col_full">
                                        <label for="register-form-repassword">Điện Thoại:</label>
                                        @Html.TextBoxFor(model => model.DienThoai, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-repassword">Tỉnh/Thành:</label>
                                        @Html.DropDownList("TinhThanh", new SelectList(new string[] { }), new { @class = "form-control", @id = "ddlProvince", @onClick = "loadDistrict(value)" })
                                        @Html.ValidationMessageFor(model => model.TinhThanh, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col_full">
                                        <label for="register-form-repassword">Quận/Huyện:</label>
                                        @Html.DropDownList("QuanHuyen", new SelectList(new string[] { }), new { @class = "form-control", @id = "ddlDistrict" })
                                        @Html.ValidationMessageFor(model => model.QuanHuyen, "", new { @class = "text-danger" })
                                    </div>
                                    
                                    <div class="col_full nobottommargin">
                                        <button class="button button-3d button-black nomargin" id="register-form-submit" name="register-form-submit" value="register">Đăng Ký</button>
                                    </div>

                                    <div class="line line-sm"></div>

                                    <div class="center">
                                        <h4 style="margin-bottom: 15px;">Liên Kết Tài Khoản:</h4>
                                        <a href="#" class="button button-rounded si-facebook si-colored">Facebook</a>
                                        <span class="hidden-xs">Hay</span>
                                        <a href="#" class="button button-rounded si-twitter si-colored">Twitter</a>
                                    </div>

                                </form>
                                }
                            </div>
                        </div>
                        <script>
                            $(document).ready(function () {
                                loadProvince()
                            });
                        </script>
                    </div>

                </div>

            </div>

        </div>

    </div>

</section><!-- #content end -->